services:
  postgres:
    image: postgres:16-alpine
    container_name: rufus-anastasii-postgres
    ports:
      - '5454:5432'
    environment:
      POSTGRES_USER: rufus
      POSTGRES_PASSWORD: anastasii
      POSTGRES_DB: rufus_anastasii
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
